### PR TITLE
Fix ice40 logic circuits

### PR DESCRIPTION
**Pull request by rsetaluri**

### CODE REVIEW

**Comment by rsetaluri** [comment]
This is in order to get parity w/ coreir target. Kind of hacky...any better way to do this?

**Comment by leonardt** [comment]
Addendum (width == None is for specifying Bit)

**Comment by leonardt** [comment]
@rsetaluri I'm going to close this since we want to preserve this interface. If you can remember, can you give me the mantle circuit that had the inconsistent interface that caused this? It suspect it's something inside logic. We should make sure that the core implementation matches the mantle40 interface

**Comment by leonardt** [comment]
Actually enabling the generic mantle tests should uncover this, so no worries if you can't remember, I should be able to find it.

**Pull request closed without merging**
