### PR TITLE
added a ready valid type constructor and a test

### PR DESCRIPTION
**Pull request by rdaly525**
It would be good to have a set of convenient type constructors. One example is ready/valid. 

Currently I just have this as a type constructor for a Tuple, but I could imagine another possible implementation is inheriting from the Tuple type itself. 

Let me know what you think.

### CODE REVIEW

**Comment by leonardt** [comment]
Seems like a good idea, this would allow us to standardize the interfaces.

Would be cool to add a custom `wire` method for the type that hooks it up properly.

@phanrahan any feedback? I'm happy to merge this in.

**Comment by rdaly525** [comment]
I merged in an axi port type constructor as well (for progress on the zynq/trenz board) and it seems to be failing on a unrelated bad gold file

**Comment by rdaly525** [comment]
Also, yeah I think a custom wiring function would work great here. Although you could probably just directly bulk wire the ready/valid/data tuple

**Comment by rdaly525** [comment]
Any issues with this PR?

**Comment by phanrahan** [comment]
I was going to add my implementation to a branch for comparison, but we can always improve what you have done.

I think this should be in magma not mantle. ready-valid is common enough that we should standardize there.

**Comment by leonardt** [comment]
Cleaning up some old branches, I'm going to move these type definitions to magma at some point in the near future.

I think the plan should be to create a `magma.types` submodule which contains the standard definition of types. Let me know if you have any comments on the specifics of how this should be done.

**Comment by leonardt** [comment]
This has been added to core magma

**Pull request closed without merging**
